// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentEnrollmentSystem.Data;

#nullable disable

namespace StudentEnrollmentSystem.Migrations
{
    [DbContext(typeof(SESContext))]
    [Migration("20230522050801_course_SP_add")]
    partial class course_SP_add
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence<int>("StudentNo")
                .StartsAt(999L);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "cc096d08-a0c0-458f-b71f-03a0db43b1bc",
                            ConcurrencyStamp = "75e31cdd-3b9f-49ec-b871-404f6ddfe72d",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "b0cbd58c-011a-4859-9762-1be1073f5935",
                            ConcurrencyStamp = "617f6179-a7b6-4c39-b494-9a73cd7b487a",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR StudentNo");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DeptID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DeptID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            DeptID = -1,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = -2,
                            DeptID = -1,
                            Name = "NULL"
                        });
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Faculty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Email = "",
                            FirstName = "NULL",
                            LastName = ""
                        });
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Section", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullSchedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Day = "Monday",
                            EndTime = "08:30 AM",
                            FullSchedule = "Monday, 07:00 AM-08:30 AM",
                            SectionCode = "MAD",
                            StartTime = "07:00 AM"
                        },
                        new
                        {
                            ID = 2,
                            Day = "Monday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Monday, 08:30 AM-10:00 AM",
                            SectionCode = "MDG",
                            StartTime = "08:30 AM"
                        },
                        new
                        {
                            ID = 3,
                            Day = "Monday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Monday, 10:00 AM-11:30 AM",
                            SectionCode = "MGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 4,
                            Day = "Monday",
                            EndTime = "01:00 PM",
                            FullSchedule = "Monday, 11:30 AM-01:00 PM",
                            SectionCode = "MJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 5,
                            Day = "Monday",
                            EndTime = "02:30 PM",
                            FullSchedule = "Monday, 01:00 PM-02:30 PM",
                            SectionCode = "MMP",
                            StartTime = "01:00 PM"
                        },
                        new
                        {
                            ID = 6,
                            Day = "Monday",
                            EndTime = "04:00 PM",
                            FullSchedule = "Monday, 02:30 PM-04:00 PM",
                            SectionCode = "MPS",
                            StartTime = "02:30 PM"
                        },
                        new
                        {
                            ID = 7,
                            Day = "Monday",
                            EndTime = "05:30 PM",
                            FullSchedule = "Monday, 04:00 PM-05:30 PM",
                            SectionCode = "MSV",
                            StartTime = "04:00 PM"
                        },
                        new
                        {
                            ID = 8,
                            Day = "Monday",
                            EndTime = "07:00 PM",
                            FullSchedule = "Monday, 05:30 PM-07:00 PM",
                            SectionCode = "MVY",
                            StartTime = "05:30 PM"
                        },
                        new
                        {
                            ID = 9,
                            Day = "Tuesday",
                            EndTime = "08:30 AM",
                            FullSchedule = "Tuesday, 07:00 AM-08:30 AM",
                            SectionCode = "TAD",
                            StartTime = "07:00 AM"
                        },
                        new
                        {
                            ID = 10,
                            Day = "Tuesday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Tuesday, 08:30 AM-10:00 AM",
                            SectionCode = "TDG",
                            StartTime = "08:30 AM"
                        },
                        new
                        {
                            ID = 11,
                            Day = "Tuesday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Tuesday, 10:00 AM-11:30 AM",
                            SectionCode = "TGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 12,
                            Day = "Tuesday",
                            EndTime = "01:00 PM",
                            FullSchedule = "Tuesday, 11:30 AM-01:00 PM",
                            SectionCode = "TJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 13,
                            Day = "Tuesday",
                            EndTime = "02:30 PM",
                            FullSchedule = "Tuesday, 01:00 PM-02:30 PM",
                            SectionCode = "TMP",
                            StartTime = "01:00 PM"
                        },
                        new
                        {
                            ID = 14,
                            Day = "Tuesday",
                            EndTime = "04:00 PM",
                            FullSchedule = "Tuesday, 02:30 PM-04:00 PM",
                            SectionCode = "TPS",
                            StartTime = "02:30 PM"
                        },
                        new
                        {
                            ID = 15,
                            Day = "Tuesday",
                            EndTime = "05:30 PM",
                            FullSchedule = "Tuesday, 04:00 PM-05:30 PM",
                            SectionCode = "TSV",
                            StartTime = "04:00 PM"
                        },
                        new
                        {
                            ID = 16,
                            Day = "Tuesday",
                            EndTime = "07:00 PM",
                            FullSchedule = "Tuesday, 05:30 PM-07:00 PM",
                            SectionCode = "TVY",
                            StartTime = "05:30 PM"
                        },
                        new
                        {
                            ID = 17,
                            Day = "Wednesday",
                            EndTime = "08:30 AM",
                            FullSchedule = "Wednesday, 07:00 AM-08:30 AM",
                            SectionCode = "WAD",
                            StartTime = "07:00 AM"
                        },
                        new
                        {
                            ID = 18,
                            Day = "Wednesday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Wednesday, 08:30 AM-10:00 AM",
                            SectionCode = "WDG",
                            StartTime = "08:30 AM"
                        },
                        new
                        {
                            ID = 19,
                            Day = "Wednesday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Wednesday, 10:00 AM-11:30 AM",
                            SectionCode = "WGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 20,
                            Day = "Wednesday",
                            EndTime = "01:00 PM",
                            FullSchedule = "Wednesday, 11:30 AM-01:00 PM",
                            SectionCode = "WJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 21,
                            Day = "Wednesday",
                            EndTime = "02:30 PM",
                            FullSchedule = "Wednesday, 01:00 PM-02:30 PM",
                            SectionCode = "WMP",
                            StartTime = "01:00 PM"
                        },
                        new
                        {
                            ID = 22,
                            Day = "Wednesday",
                            EndTime = "04:00 PM",
                            FullSchedule = "Wednesday, 02:30 PM-04:00 PM",
                            SectionCode = "WPS",
                            StartTime = "02:30 PM"
                        },
                        new
                        {
                            ID = 23,
                            Day = "Wednesday",
                            EndTime = "05:30 PM",
                            FullSchedule = "Wednesday, 04:00 PM-05:30 PM",
                            SectionCode = "WSV",
                            StartTime = "04:00 PM"
                        },
                        new
                        {
                            ID = 24,
                            Day = "Wednesday",
                            EndTime = "07:00 PM",
                            FullSchedule = "Wednesday, 05:30 PM-07:00 PM",
                            SectionCode = "WVY",
                            StartTime = "05:30 PM"
                        },
                        new
                        {
                            ID = 25,
                            Day = "Thursday",
                            EndTime = "08:30 AM",
                            FullSchedule = "Thursday, 07:00 AM-08:30 AM",
                            SectionCode = "HAD",
                            StartTime = "07:00 AM"
                        },
                        new
                        {
                            ID = 26,
                            Day = "Thursday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Thursday, 08:30 AM-10:00 AM",
                            SectionCode = "HDG",
                            StartTime = "08:30 AM"
                        },
                        new
                        {
                            ID = 27,
                            Day = "Thursday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Thursday, 10:00 AM-11:30 AM",
                            SectionCode = "HGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 28,
                            Day = "Thursday",
                            EndTime = "01:00 PM",
                            FullSchedule = "Thursday, 11:30 AM-01:00 PM",
                            SectionCode = "HJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 29,
                            Day = "Thursday",
                            EndTime = "02:30 PM",
                            FullSchedule = "Thursday, 01:00 PM-02:30 PM",
                            SectionCode = "HMP",
                            StartTime = "01:00 PM"
                        },
                        new
                        {
                            ID = 30,
                            Day = "Thursday",
                            EndTime = "04:00 PM",
                            FullSchedule = "Thursday, 02:30 PM-04:00 PM",
                            SectionCode = "HPS",
                            StartTime = "02:30 PM"
                        },
                        new
                        {
                            ID = 31,
                            Day = "Thursday",
                            EndTime = "05:30 PM",
                            FullSchedule = "Thursday, 04:00 PM-05:30 PM",
                            SectionCode = "HSV",
                            StartTime = "04:00 PM"
                        },
                        new
                        {
                            ID = 32,
                            Day = "Thursday",
                            EndTime = "07:00 PM",
                            FullSchedule = "Thursday, 05:30 PM-07:00 PM",
                            SectionCode = "HVY",
                            StartTime = "05:30 PM"
                        },
                        new
                        {
                            ID = 33,
                            Day = "Friday",
                            EndTime = "08:30 AM",
                            FullSchedule = "Friday, 07:00 AM-08:30 AM",
                            SectionCode = "FAD",
                            StartTime = "07:00 AM"
                        },
                        new
                        {
                            ID = 34,
                            Day = "Friday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Friday, 08:30 AM-10:00 AM",
                            SectionCode = "FDG",
                            StartTime = "08:30 AM"
                        },
                        new
                        {
                            ID = 35,
                            Day = "Friday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Friday, 10:00 AM-11:30 AM",
                            SectionCode = "FGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 36,
                            Day = "Friday",
                            EndTime = "01:00 PM",
                            FullSchedule = "Friday, 11:30 AM-01:00 PM",
                            SectionCode = "FJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 37,
                            Day = "Friday",
                            EndTime = "02:30 PM",
                            FullSchedule = "Friday, 01:00 PM-02:30 PM",
                            SectionCode = "FMP",
                            StartTime = "01:00 PM"
                        },
                        new
                        {
                            ID = 38,
                            Day = "Friday",
                            EndTime = "04:00 PM",
                            FullSchedule = "Friday, 02:30 PM-04:00 PM",
                            SectionCode = "FPS",
                            StartTime = "02:30 PM"
                        },
                        new
                        {
                            ID = 39,
                            Day = "Friday",
                            EndTime = "05:30 PM",
                            FullSchedule = "Friday, 04:00 PM-05:30 PM",
                            SectionCode = "FSV",
                            StartTime = "04:00 PM"
                        },
                        new
                        {
                            ID = 40,
                            Day = "Friday",
                            EndTime = "07:00 PM",
                            FullSchedule = "Friday, 05:30 PM-07:00 PM",
                            SectionCode = "FVY",
                            StartTime = "05:30 PM"
                        },
                        new
                        {
                            ID = 41,
                            Day = "Saturday",
                            EndTime = "08:30 AM",
                            FullSchedule = "Saturday, 07:00 AM-08:30 AM",
                            SectionCode = "SAD",
                            StartTime = "07:00 AM"
                        },
                        new
                        {
                            ID = 42,
                            Day = "Saturday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Saturday, 08:30 AM-10:00 AM",
                            SectionCode = "SDG",
                            StartTime = "08:30 AM"
                        },
                        new
                        {
                            ID = 43,
                            Day = "Saturday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Saturday, 10:00 AM-11:30 AM",
                            SectionCode = "SGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 44,
                            Day = "Saturday",
                            EndTime = "01:00 PM",
                            FullSchedule = "Saturday, 11:30 AM-01:00 PM",
                            SectionCode = "SJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 45,
                            Day = "Saturday",
                            EndTime = "02:30 PM",
                            FullSchedule = "Saturday, 01:00 PM-02:30 PM",
                            SectionCode = "SMP",
                            StartTime = "01:00 PM"
                        },
                        new
                        {
                            ID = 46,
                            Day = "Saturday",
                            EndTime = "04:00 PM",
                            FullSchedule = "Saturday, 02:30 PM-04:00 PM",
                            SectionCode = "SPS",
                            StartTime = "02:30 PM"
                        },
                        new
                        {
                            ID = 47,
                            Day = "Saturday",
                            EndTime = "05:30 PM",
                            FullSchedule = "Saturday, 04:00 PM-05:30 PM",
                            SectionCode = "SSV",
                            StartTime = "04:00 PM"
                        },
                        new
                        {
                            ID = 48,
                            Day = "Saturday",
                            EndTime = "07:00 PM",
                            FullSchedule = "Saturday, 05:30 PM-07:00 PM",
                            SectionCode = "SVY",
                            StartTime = "05:30 PM"
                        },
                        new
                        {
                            ID = -1,
                            Day = "",
                            EndTime = "",
                            FullSchedule = "NULL",
                            SectionCode = "NULL",
                            StartTime = ""
                        });
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.StudentSubject", b =>
                {
                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("StudentID", "SubjectID");

                    b.HasIndex("SubjectID");

                    b.ToTable("StudentSubjects");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Subject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ClassSize")
                        .HasColumnType("int");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int?>("FacultyID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectionID")
                        .HasColumnType("int");

                    b.Property<int>("StudentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.HasIndex("FacultyID");

                    b.HasIndex("SectionID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentEnrollmentSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.ApplicationUser", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Course", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.StudentSubject", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.ApplicationUser", "Student")
                        .WithMany("Subjects")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentEnrollmentSystem.Models.Subject", "Subject")
                        .WithMany("Students")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Subject", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.Course", "Course")
                        .WithMany("Subjects")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentEnrollmentSystem.Models.Faculty", "Faculty")
                        .WithMany("Subjects")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentEnrollmentSystem.Models.Section", "Section")
                        .WithMany("Subjects")
                        .HasForeignKey("SectionID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("Faculty");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.ApplicationUser", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Course", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Department", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Faculty", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Section", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Subject", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
