// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentEnrollmentSystem.Data;

#nullable disable

namespace StudentEnrollmentSystem.Migrations
{
    [DbContext(typeof(SESContext))]
    [Migration("20230424100724_reseed_sections")]
    partial class reseed_sections
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence<int>("StudentNo")
                .StartsAt(999L);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "03ee7b87-22be-480b-b789-5ade53e3a0d3",
                            ConcurrencyStamp = "2c71f256-e52e-4ce5-92b9-c587ede3b5f2",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "89e1bbc4-24fc-4eef-b8cc-6020dc9b4286",
                            ConcurrencyStamp = "f6e4f24d-924b-4ad9-8f65-120ccc7933e0",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR StudentNo");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DeptID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DeptID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            DeptID = -1,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Faculty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DeptID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DeptID");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Section", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullSchedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Day = "Monday",
                            EndTime = "8:30 AM",
                            FullSchedule = "Monday, 7:00 AM-8:30 AM",
                            SectionCode = "MAD",
                            StartTime = "7:00 AM"
                        },
                        new
                        {
                            ID = 2,
                            Day = "Monday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Monday, 8:30 AM-10:00 AM",
                            SectionCode = "MDG",
                            StartTime = "8:30 AM"
                        },
                        new
                        {
                            ID = 3,
                            Day = "Monday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Monday, 10:00 AM-11:30 AM",
                            SectionCode = "MGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 4,
                            Day = "Monday",
                            EndTime = "1:00 PM",
                            FullSchedule = "Monday, 11:30 AM-1:00 PM",
                            SectionCode = "MJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 5,
                            Day = "Monday",
                            EndTime = "2:30 PM",
                            FullSchedule = "Monday, 1:00 PM-2:30 PM",
                            SectionCode = "MMP",
                            StartTime = "1:00 PM"
                        },
                        new
                        {
                            ID = 6,
                            Day = "Monday",
                            EndTime = "4:00 PM",
                            FullSchedule = "Monday, 2:30 PM-4:00 PM",
                            SectionCode = "MPS",
                            StartTime = "2:30 PM"
                        },
                        new
                        {
                            ID = 7,
                            Day = "Monday",
                            EndTime = "5:30 PM",
                            FullSchedule = "Monday, 4:00 PM-5:30 PM",
                            SectionCode = "MSV",
                            StartTime = "4:00 PM"
                        },
                        new
                        {
                            ID = 8,
                            Day = "Monday",
                            EndTime = "7:00 PM",
                            FullSchedule = "Monday, 5:30 PM-7:00 PM",
                            SectionCode = "MVY",
                            StartTime = "5:30 PM"
                        },
                        new
                        {
                            ID = 9,
                            Day = "Tuesday",
                            EndTime = "8:30 AM",
                            FullSchedule = "Tuesday, 7:00 AM-8:30 AM",
                            SectionCode = "TAD",
                            StartTime = "7:00 AM"
                        },
                        new
                        {
                            ID = 10,
                            Day = "Tuesday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Tuesday, 8:30 AM-10:00 AM",
                            SectionCode = "TDG",
                            StartTime = "8:30 AM"
                        },
                        new
                        {
                            ID = 11,
                            Day = "Tuesday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Tuesday, 10:00 AM-11:30 AM",
                            SectionCode = "TGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 12,
                            Day = "Tuesday",
                            EndTime = "1:00 PM",
                            FullSchedule = "Tuesday, 11:30 AM-1:00 PM",
                            SectionCode = "TJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 13,
                            Day = "Tuesday",
                            EndTime = "2:30 PM",
                            FullSchedule = "Tuesday, 1:00 PM-2:30 PM",
                            SectionCode = "TMP",
                            StartTime = "1:00 PM"
                        },
                        new
                        {
                            ID = 14,
                            Day = "Tuesday",
                            EndTime = "4:00 PM",
                            FullSchedule = "Tuesday, 2:30 PM-4:00 PM",
                            SectionCode = "TPS",
                            StartTime = "2:30 PM"
                        },
                        new
                        {
                            ID = 15,
                            Day = "Tuesday",
                            EndTime = "5:30 PM",
                            FullSchedule = "Tuesday, 4:00 PM-5:30 PM",
                            SectionCode = "TSV",
                            StartTime = "4:00 PM"
                        },
                        new
                        {
                            ID = 16,
                            Day = "Tuesday",
                            EndTime = "7:00 PM",
                            FullSchedule = "Tuesday, 5:30 PM-7:00 PM",
                            SectionCode = "TVY",
                            StartTime = "5:30 PM"
                        },
                        new
                        {
                            ID = 17,
                            Day = "Wednesday",
                            EndTime = "8:30 AM",
                            FullSchedule = "Wednesday, 7:00 AM-8:30 AM",
                            SectionCode = "WAD",
                            StartTime = "7:00 AM"
                        },
                        new
                        {
                            ID = 18,
                            Day = "Wednesday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Wednesday, 8:30 AM-10:00 AM",
                            SectionCode = "WDG",
                            StartTime = "8:30 AM"
                        },
                        new
                        {
                            ID = 19,
                            Day = "Wednesday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Wednesday, 10:00 AM-11:30 AM",
                            SectionCode = "WGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 20,
                            Day = "Wednesday",
                            EndTime = "1:00 PM",
                            FullSchedule = "Wednesday, 11:30 AM-1:00 PM",
                            SectionCode = "WJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 21,
                            Day = "Wednesday",
                            EndTime = "2:30 PM",
                            FullSchedule = "Wednesday, 1:00 PM-2:30 PM",
                            SectionCode = "WMP",
                            StartTime = "1:00 PM"
                        },
                        new
                        {
                            ID = 22,
                            Day = "Wednesday",
                            EndTime = "4:00 PM",
                            FullSchedule = "Wednesday, 2:30 PM-4:00 PM",
                            SectionCode = "WPS",
                            StartTime = "2:30 PM"
                        },
                        new
                        {
                            ID = 23,
                            Day = "Wednesday",
                            EndTime = "5:30 PM",
                            FullSchedule = "Wednesday, 4:00 PM-5:30 PM",
                            SectionCode = "WSV",
                            StartTime = "4:00 PM"
                        },
                        new
                        {
                            ID = 24,
                            Day = "Wednesday",
                            EndTime = "7:00 PM",
                            FullSchedule = "Wednesday, 5:30 PM-7:00 PM",
                            SectionCode = "WVY",
                            StartTime = "5:30 PM"
                        },
                        new
                        {
                            ID = 25,
                            Day = "Thursday",
                            EndTime = "8:30 AM",
                            FullSchedule = "Thursday, 7:00 AM-8:30 AM",
                            SectionCode = "HAD",
                            StartTime = "7:00 AM"
                        },
                        new
                        {
                            ID = 26,
                            Day = "Thursday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Thursday, 8:30 AM-10:00 AM",
                            SectionCode = "HDG",
                            StartTime = "8:30 AM"
                        },
                        new
                        {
                            ID = 27,
                            Day = "Thursday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Thursday, 10:00 AM-11:30 AM",
                            SectionCode = "HGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 28,
                            Day = "Thursday",
                            EndTime = "1:00 PM",
                            FullSchedule = "Thursday, 11:30 AM-1:00 PM",
                            SectionCode = "HJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 29,
                            Day = "Thursday",
                            EndTime = "2:30 PM",
                            FullSchedule = "Thursday, 1:00 PM-2:30 PM",
                            SectionCode = "HMP",
                            StartTime = "1:00 PM"
                        },
                        new
                        {
                            ID = 30,
                            Day = "Thursday",
                            EndTime = "4:00 PM",
                            FullSchedule = "Thursday, 2:30 PM-4:00 PM",
                            SectionCode = "HPS",
                            StartTime = "2:30 PM"
                        },
                        new
                        {
                            ID = 31,
                            Day = "Thursday",
                            EndTime = "5:30 PM",
                            FullSchedule = "Thursday, 4:00 PM-5:30 PM",
                            SectionCode = "HSV",
                            StartTime = "4:00 PM"
                        },
                        new
                        {
                            ID = 32,
                            Day = "Thursday",
                            EndTime = "7:00 PM",
                            FullSchedule = "Thursday, 5:30 PM-7:00 PM",
                            SectionCode = "HVY",
                            StartTime = "5:30 PM"
                        },
                        new
                        {
                            ID = 33,
                            Day = "Friday",
                            EndTime = "8:30 AM",
                            FullSchedule = "Friday, 7:00 AM-8:30 AM",
                            SectionCode = "FAD",
                            StartTime = "7:00 AM"
                        },
                        new
                        {
                            ID = 34,
                            Day = "Friday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Friday, 8:30 AM-10:00 AM",
                            SectionCode = "FDG",
                            StartTime = "8:30 AM"
                        },
                        new
                        {
                            ID = 35,
                            Day = "Friday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Friday, 10:00 AM-11:30 AM",
                            SectionCode = "FGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 36,
                            Day = "Friday",
                            EndTime = "1:00 PM",
                            FullSchedule = "Friday, 11:30 AM-1:00 PM",
                            SectionCode = "FJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 37,
                            Day = "Friday",
                            EndTime = "2:30 PM",
                            FullSchedule = "Friday, 1:00 PM-2:30 PM",
                            SectionCode = "FMP",
                            StartTime = "1:00 PM"
                        },
                        new
                        {
                            ID = 38,
                            Day = "Friday",
                            EndTime = "4:00 PM",
                            FullSchedule = "Friday, 2:30 PM-4:00 PM",
                            SectionCode = "FPS",
                            StartTime = "2:30 PM"
                        },
                        new
                        {
                            ID = 39,
                            Day = "Friday",
                            EndTime = "5:30 PM",
                            FullSchedule = "Friday, 4:00 PM-5:30 PM",
                            SectionCode = "FSV",
                            StartTime = "4:00 PM"
                        },
                        new
                        {
                            ID = 40,
                            Day = "Friday",
                            EndTime = "7:00 PM",
                            FullSchedule = "Friday, 5:30 PM-7:00 PM",
                            SectionCode = "FVY",
                            StartTime = "5:30 PM"
                        },
                        new
                        {
                            ID = 41,
                            Day = "Saturday",
                            EndTime = "8:30 AM",
                            FullSchedule = "Saturday, 7:00 AM-8:30 AM",
                            SectionCode = "SAD",
                            StartTime = "7:00 AM"
                        },
                        new
                        {
                            ID = 42,
                            Day = "Saturday",
                            EndTime = "10:00 AM",
                            FullSchedule = "Saturday, 8:30 AM-10:00 AM",
                            SectionCode = "SDG",
                            StartTime = "8:30 AM"
                        },
                        new
                        {
                            ID = 43,
                            Day = "Saturday",
                            EndTime = "11:30 AM",
                            FullSchedule = "Saturday, 10:00 AM-11:30 AM",
                            SectionCode = "SGJ",
                            StartTime = "10:00 AM"
                        },
                        new
                        {
                            ID = 44,
                            Day = "Saturday",
                            EndTime = "1:00 PM",
                            FullSchedule = "Saturday, 11:30 AM-1:00 PM",
                            SectionCode = "SJM",
                            StartTime = "11:30 AM"
                        },
                        new
                        {
                            ID = 45,
                            Day = "Saturday",
                            EndTime = "2:30 PM",
                            FullSchedule = "Saturday, 1:00 PM-2:30 PM",
                            SectionCode = "SMP",
                            StartTime = "1:00 PM"
                        },
                        new
                        {
                            ID = 46,
                            Day = "Saturday",
                            EndTime = "4:00 PM",
                            FullSchedule = "Saturday, 2:30 PM-4:00 PM",
                            SectionCode = "SPS",
                            StartTime = "2:30 PM"
                        },
                        new
                        {
                            ID = 47,
                            Day = "Saturday",
                            EndTime = "5:30 PM",
                            FullSchedule = "Saturday, 4:00 PM-5:30 PM",
                            SectionCode = "SSV",
                            StartTime = "4:00 PM"
                        },
                        new
                        {
                            ID = 48,
                            Day = "Saturday",
                            EndTime = "7:00 PM",
                            FullSchedule = "Saturday, 5:30 PM-7:00 PM",
                            SectionCode = "SVY",
                            StartTime = "5:30 PM"
                        });
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.StudentSubject", b =>
                {
                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("StudentID", "SubjectID");

                    b.HasIndex("SubjectID");

                    b.ToTable("StudentSubjects");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Subject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ClassSize")
                        .HasColumnType("int");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectionID")
                        .HasColumnType("int");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.HasIndex("FacultyID");

                    b.HasIndex("SectionID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentEnrollmentSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.ApplicationUser", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Course", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Faculty", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.Department", "Department")
                        .WithMany("Faculties")
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.StudentSubject", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.ApplicationUser", "Student")
                        .WithMany("Subjects")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentEnrollmentSystem.Models.Subject", "Subject")
                        .WithMany("Students")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Subject", b =>
                {
                    b.HasOne("StudentEnrollmentSystem.Models.Course", "Course")
                        .WithMany("Subjects")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentEnrollmentSystem.Models.Faculty", "Faculty")
                        .WithMany("Subjects")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudentEnrollmentSystem.Models.Section", "Section")
                        .WithMany("Subjects")
                        .HasForeignKey("SectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Faculty");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.ApplicationUser", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Course", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Faculties");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Faculty", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Section", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Models.Subject", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
